### ISSUE TITLE
Errors on imports

### ISSUE THREAD

**Issue by Valerio-Colombo** [LucasAlegre/mbcd#1]
Hi,
when executing the code there are some imports that are not found in the file mbcd/models/bnn.py.
```
16 from drl_cd.models.utils import get_required_argument, TensorStandardScaler
17 from drl_cd.models.fc import FC
18
19 from drl_cd.utils.logger import Progress, Silent
```

`drl_cd` doesn't exist. I suppose it has to be substituted by `mbcd`. Is this right?

Furthermore, in the file experiments/mbcd_run.py at line
```
70 model.deepRLCD.save_current()
71 model.deepRLCD.save_models()
```
`deepRLCD` can't be found and the execution stops.

```
Traceback (most recent call last):
  File "/home/valerio/PycharmProjects/mbcd/experiments/mbcd_run.py", line 95, in <module>
    main(config)
  File "/home/valerio/PycharmProjects/mbcd/experiments/mbcd_run.py", line 71, in main
    model.deepRLCD.save_current()
AttributeError: 'SAC' object has no attribute 'deepRLCD'
```

**Comment by LucasAlegre** [comment]
Hi,

Thank you for pointing this! I renamed many variables before publishing the source code, I must have let this pass.
I fixed this in the last commit, but let me know if you encounter any other issues!

**Comment by Valerio-Colombo** [comment]
Thank you very much. Now everything seems to work.
